--changeset COMMENTS:1

CREATE TABLE COMMENTS (
    ID SERIAL NOT NULL,
    CREATED_AT TIMESTAMP(6) WITH TIME ZONE,
    CREATED_BY SMALLINT,
    UPDATED_AT TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY SMALLINT,
    COMMENT VARCHAR(255),
    MODULE_NAME VARCHAR(50),
    ENTITY_NAME VARCHAR(50),
    ENTITY_ID SMALLINT,
    IS_DELETED BOOLEAN DEFAULT '0',

    CONSTRAINT COMMENTS_PK PRIMARY KEY (ID)
);